"""Scenario harness package for Claudarama."""

from claudarama.scenario.cli import run_checker_cli
from claudarama.scenario.judge import (
    CheckResult,
    ExcludesSelfTestResult,
    JudgeResult,
    evaluate_exclude_pattern,
    evaluate_excludes,
    evaluate_include_pattern,
    evaluate_includes,
    parse_judge_output,
    self_test_all_excludes,
    self_test_excludes,
    strict_json_judge,
    verify_excludes_pattern,
)
from claudarama.scenario.runner import (
    ComparisonSummary,
    LLMInvoker,
    MockInvoker,
    ScenarioComparison,
    ScenarioEvaluationResult,
    SingleTurnResult,
    evaluate_against_ref,
    evaluate_scenario,
    run_scenario_file,
)
from claudarama.scenario.sealing import (
    SealingResult,
    SealingViolation,
    compare_scenario_constraints,
    compare_scenario_sets,
    load_scenarios_from_directory,
    load_scenarios_from_git,
    run_sealing_cli,
)
from claudarama.scenario.validator import (
    Scenario,
    ScenarioChecks,
    ScenarioValidationError,
    ValidationResult,
    load_scenario,
    validate_scenario,
    validate_scenario_file,
    validate_scenario_paths,
)

__all__ = [
    "CheckResult",
    "ComparisonSummary",
    "ExcludesSelfTestResult",
    "JudgeResult",
    "LLMInvoker",
    "MockInvoker",
    "Scenario",
    "ScenarioChecks",
    "ScenarioComparison",
    "ScenarioEvaluationResult",
    "ScenarioValidationError",
    "SealingResult",
    "SealingViolation",
    "SingleTurnResult",
    "ValidationResult",
    "compare_scenario_constraints",
    "compare_scenario_sets",
    "evaluate_against_ref",
    "evaluate_exclude_pattern",
    "evaluate_excludes",
    "evaluate_include_pattern",
    "evaluate_includes",
    "evaluate_scenario",
    "load_scenario",
    "load_scenarios_from_directory",
    "load_scenarios_from_git",
    "parse_judge_output",
    "run_checker_cli",
    "run_scenario_file",
    "run_sealing_cli",
    "self_test_all_excludes",
    "self_test_excludes",
    "strict_json_judge",
    "validate_scenario",
    "validate_scenario_file",
    "validate_scenario_paths",
    "verify_excludes_pattern",
]
